// 一個業務模組是一個 ownership 邊界，不代表一個獨立微服務。
export const modules = [
  {
    id: "identity",
    title: "身份與邀請",
    tables: ["operators", "agents", "api_keys", "wallet_challenges"],
    responsibility: "API key、scope、wallet binding；不授予資金轉出權",
    status: "planned",
  },
  {
    id: "evidence",
    title: "資料與證據",
    tables: ["evidence", "source_allowlists"],
    responsibility: "來源擷取、不可覆寫 bytes、hash 與公開權限",
    status: "planned",
  },
  {
    id: "discovery",
    title: "候選研究",
    tables: ["candidates", "candidate_revisions"],
    responsibility: "掃描、GM_LT_V1、驗證、修訂與人工審查",
    status: "planned",
  },
  {
    id: "markets",
    title: "市場與規格",
    tables: ["market_specs", "markets"],
    responsibility: "核准後凍結規格、建立市場 intent、LIVE/REPLAY 分離",
    status: "planned",
  },
  {
    id: "forecasts",
    title: "預測與基準",
    tables: ["forecast_windows", "forecasts", "model_runs"],
    responsibility: "兩個內部 forecaster、獨立 baseline、外部 agent、窗口封存",
    status: "planned",
  },
  {
    id: "budgets",
    title: "成本與預算",
    tables: ["question_budgets", "daily_budgets", "cost_entries"],
    responsibility: "USD 微單位、原子 reservation、unknown cost 保留",
    status: "planned",
  },
  {
    id: "trading",
    title: "RFQ 與交易政策",
    tables: [
      "rfqs",
      "quotes",
      "collateral_reservations",
      "mandates",
      "risk_reservations",
    ],
    responsibility: "報價、資金預留、mandate；不託管外部 taker",
    status: "planned",
  },
  {
    id: "chain",
    title: "鏈上追蹤與投影",
    tables: [
      "deployments",
      "chain_transactions",
      "chain_blocks",
      "chain_events",
      "positions_projection",
      "chain_cursors",
    ],
    responsibility: "canonical events、reorg 回退、reconciliation、交易狀態",
    status: "planned",
  },
  {
    id: "resolution",
    title: "結果與爭議",
    tables: ["resolution_reports", "resolution_actions"],
    responsibility: "證據報告、人工裁決流程與 keeper 排程；結果以鏈為準",
    status: "planned",
  },
  {
    id: "faucet",
    title: "測試資產",
    tables: ["faucet_claims"],
    responsibility: "邀請地址額度、mint intent 與 gas 限制",
    status: "planned",
  },
  {
    id: "analytics",
    title: "品質與統計",
    tables: ["evaluation_runs", "score_entries"],
    responsibility: "Brier、缺失率、成本與採用統計；排除 INVALID 評分",
    status: "planned",
  },
  {
    id: "operations",
    title: "營運與稽核",
    tables: ["audit_log", "idempotency_records", "jobs", "outbox"],
    responsibility: "工作重試、管理稽核、告警、備份與恢復",
    status: "planned",
  },
] as const;
export type ModuleId = (typeof modules)[number]["id"];
