[profile.default]
src = "src"
test = "test"
solc_version = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
chain_id = 84532
libs = ["../node_modules"]
remappings = ["@openzeppelin/contracts/=../node_modules/@openzeppelin/contracts/"]

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 128
depth = 64
fail_on_revert = true
